baseURL = "https://my-philosophy-site-eta.vercel.app/"
languageCode = "ja-jp"
title = "Mizue Osanai"
theme = "hermit"

enableRobotsTXT = true
pygmentsCodefences = true
pygmentsUseClasses = true

[author]
  name = "Mizue Osanai"

[params]
  dateform = "2006-01-02"
  dateformShort = "Jan 2"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  homeTitle = "Mizue Osanai"
  subtitle = "Welcome to my site."
  themeColor = "light"
  defaultTheme = "light"
  socialCircle = true

  # アバター（プロフィール画像）がある場合の指定（static/avatar.png 等があれば適用されます）
  # avatar = "avatar.png"

  [params.author]
    name = "Mizue Osanai"

[[menu.main]]
  name = "Notes"
  url = "notes/"
  weight = 10

[[menu.main]]
  name = "Works"
  url = "works/"
  weight = 20

[[menu.main]]
  name = "About"
  url = "about/"
  weight = 30
