baseURL = "https://my-philosophy-site-eta.vercel.app/"
languageCode = "ja-jp"
title = "my-philosophy-site"
theme = "hermit"

enableRobotsTXT = true
pygmentsCodefences = true
pygmentsUseClasses = true

[author]
  name = "mizue"

[params]
  dateform = "2006-01-02"
  dateformShort = "Jan 2"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  homeTitle = "my-philosophy-site"
  subtitle = "Welcome to my philosophy site."
  socialCircle = true

  [params.author]
    name = "mizue"

[[menu.main]]
  name = "Notes"
  url = "posts/"
  weight = 10

[[menu.main]]
  name = "Work"
  url = "work/"
  weight = 20

[[menu.main]]
  name = "About"
  url = "about/"
  weight = 30
